<footer>
    <div class="footer-links">
        <a href="https://webtechprojectsassignment1.atlassian.net/jira/software/projects/SCRUM/boards/1">Mission Status (Jira)</a> |
        <a href="https://github.com/Qwofii/Web-Technology-Proj.git">Ship Code (GitHub)</a> |
        <a href="mailto:106499895@student.swin.edu.au">Contact (support@nexcare.galaxy)</a>
    </div>
    <p style="opacity: 0.85;">&copy; 2026 NexCare Galactic. Milky Way Federation Approved.</p>
</footer>

