<header>
        <nav class="navbar">
            <div class="brand-area">
                <a href="https://qwofii.github.io/Web-Technology-Proj/index.html">
                <img src="images/logo.png" alt="NexCare Logo" class="logo-img"></a>
                <div>
                    <p class="brand-name">NexCare Galactic Services</p>
                    <p class="brand-slogan">Delivering care across the Andromeda Galaxy.</p>
                </div>
            </div>
            <ul class="nav-links">
                <li><a href="https://qwofii.github.io/Web-Technology-Proj/index.html">Home</a></li>
                <li><a href="https://qwofii.github.io/Web-Technology-Proj/about.html">About</a></li>
                <li><a href="https://qwofii.github.io/Web-Technology-Proj/jobs.html">Jobs</a></li>
                <li><a href="https://qwofii.github.io/Web-Technology-Proj/apply.html">Apply</a></li>
                <li><a href="login.php">Log in</a></li>
            </ul>
        </nav>
    </header>
    