<a id="light"></a>
<header>
    <nav class="navbar">
        <div class="brand-area">
            <a href="index.php">
            <img src="images/logo.png" alt="NexCare Logo" class="logo-img"></a>
            <div>
                <p class="brand-name">NexCare Galactic Services</p>
                <p class="brand-slogan">Delivering care across the Andromeda Galaxy.</p>
            </div>
        </div>
        <ul class="nav-links">
            <li><a href="index.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Apply</a></li>
            <li><a href="login.php">Log in</a></li>
            <li>
                <a class="theme-switch switch-to-dark" href="#dark">🌙 Dark Mode</a>
                <a class="theme-switch switch-to-light" href="#light">☀️ Light Mode</a>
            </li>
        </ul>
    </nav>
</header>